#!/bin/bash
#
# Starts a Selenium-RC headless environment
# License: https://github.com/amenk/SelfScripts/blob/master/LICENSE.md

#
# BETA
# Fixmes:
# - We should take care of running the environment under a non-priviledged user
# you have to create an /etc/selenium-headless.conf containing something like that:
#
#LOG=/var/log/selenium.log
#DEBUGLOG=/var/log/selenium-debug.log
#SELENIUM_JAR=/opt/selenium-server-standalone.jar
#FIREFOX_TEMPLATE=/home/myuser/.mozilla/firefox/abcdefg.selenium/
#
#
# Source function library.
. /lib/lsb/init-functions


. /etc/selenium-headless.conf

DISPLAY_NO=99
JAVA=/usr/bin/java
XVFB=/usr/bin/Xvfb
NOHUP=/usr/bin/nohup
SELENIUMPIDFILE=/var/run/Selenium-RC.pid

start() {
        log_daemon_msg "Starting Xvfb"
	daemon --dbglog=$LOG --errlog=$LOG --stdout=$LOG --stderr=$LOG\
		--name Xvfb -- $XVFB :$DISPLAY_NO -ac -screen 0 1024x768x8
	log_end_msg $?
        log_daemon_msg "Starting Selenium RC"
	export DISPLAY=:$DISPLAY_NO
	$NOHUP $JAVA -jar $SELENIUM_JAR -log $DEBUGLOG -browserSideLog -firefoxProfileTemplate $FIREFOX_TEMPLATE > $LOG 2>&1 & 
	echo $! > $SELENIUMPIDFILE
	log_end_msg $?
        return
}

stop() {
        log_daemon_msg "Stopping Selenium RC"
	SELENIUMPID=`cat $SELENIUMPIDFILE`
	kill $SELENIUMPID
	rm $SELENIUMPIDFILE
	log_end_msg $?

	log_daemon_msg "Stopping Xvfb"
	daemon --stop --name Xvfb
	log_end_msg $?
        return
}

status() {
	daemon -v10 --running --name Xvfb

	if [ ! -e $SELENIUMPIDFILE ]; then
		echo "Selenium not running"
		return
	fi
	
	SELENIUMPID=`cat $SELENIUMPIDFILE`

	if [ -d /proc/$SELENIUMPID ]; then
		echo "Selenium running with PID $SELENIUMPID"
	else
		echo "Selenium not running: But PID file with PID $SELENIUMPID exists"
	fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
	status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|status|restart"
        exit 1
        ;;
esac
exit $?
